# Generated by Django 5.2 on 2025-06-23 20:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_fechamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_fechamento', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('seguidor', 'Seguidor'), ('seguimista', 'Seguimista')], max_length=20)),
                ('equipe', models.CharField(blank=True, max_length=100, null=True)),
                ('cor', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estoque', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('comida', 'Comida'), ('bebida', 'Bebida Não Alcoólica'), ('doce', 'Doce'), ('decoracao', 'Decoração')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteResumo',
            fields=[
            ],
            options={
                'verbose_name': 'Resumo de Vendas',
                'verbose_name_plural': 'Resumo de Vendas',
                'ordering': ['nome'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mercado.cliente',),
        ),
        migrations.CreateModel(
            name='SaidaCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=255)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='mercado.caixa')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='mercado.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.produto')),
            ],
        ),
    ]
