# Generated by Django 5.2.3 on 2025-06-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_alter_caixa_data_fechamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro')], default='dinheiro', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='troco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
