# Generated by Django 5.2.3 on 2025-06-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_venda_forma_pagamento_venda_troco'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Informe quanto o cliente pagou (somente se for dinheiro).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro')], default='dinheiro', max_length=10),
        ),
    ]
