# Generated by Django 5.2.3 on 2025-07-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0004_venda_valor_pago_alter_venda_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('bebida', 'Bebida Não Alcoólica'), ('doces', 'Doces'), ('acessórios', 'Acessórios')], max_length=20),
        ),
    ]
