# Generated by Django 5.2 on 2025-07-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0006_logentryproxy_historicalproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoVendaDia',
            fields=[
            ],
            options={
                'verbose_name': 'Resumo por Dia',
                'verbose_name_plural': 'Resumo por Dia',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mercado.venda',),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro'), ('ultimo dia', 'Ultimo Dia')], default='dinheiro', max_length=10),
        ),
    ]
