# Generated by Django 5.2 on 2025-07-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0008_alter_venda_forma_pagamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumoVendaDia',
        ),
    ]
