# Generated by Django 5.2 on 2025-07-11 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0010_remove_venda_produto_remove_venda_quantidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoVendaDia',
            fields=[
            ],
            options={
                'verbose_name': 'Resumo por Dia',
                'verbose_name_plural': 'Resumo por Dia',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mercado.venda',),
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mercado.produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='ItemVenda',
        ),
    ]
