# Generated by Django 5.2 on 2025-07-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0012_itemvenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
    ]
