# Generated by Django 5.2 on 2025-07-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0013_remove_cliente_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumoVendaDia',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
