# Generated by Django 5.2 on 2025-07-11 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0014_delete_resumovendadia_remove_itemvenda_valor_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercado.produto'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
