# Generated by Django 5.2.3 on 2025-07-15 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0015_alter_itemvenda_produto_alter_itemvenda_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Informe quanto o cliente pagou (somente se for dinheiro).', max_digits=10, null=True),
        ),
    ]
