# Generated by Django 5.2.3 on 2025-07-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0017_venda_valor_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaidaCaixa',
        ),
    ]
