# Generated by Django 5.2.3 on 2025-07-17 22:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0018_delete_saidacaixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='saldo_devedor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
