# Generated by Django 5.2 on 2025-07-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0019_venda_pago_venda_saldo_devedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduto',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('bebida', 'Bebida Não Alcoólica'), ('doces', 'Doces'), ('acessórios', 'Acessórios'), ('combos', 'Combos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('bebida', 'Bebida Não Alcoólica'), ('doces', 'Doces'), ('acessórios', 'Acessórios'), ('combos', 'Combos')], max_length=20),
        ),
    ]
