# Generated by Django 5.2 on 2025-08-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0020_alter_historicalproduto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduto',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('bebida_nao_alcoolica', 'Bebida Não Alcoólica'), ('doces', 'Doces'), ('acessorios', 'Acessórios'), ('bebida_alcoolica', 'Bebida Alcoólica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('bebida_nao_alcoolica', 'Bebida Não Alcoólica'), ('doces', 'Doces'), ('acessorios', 'Acessórios'), ('bebida_alcoolica', 'Bebida Alcoólica')], max_length=20),
        ),
    ]
