# Generated by Django 5.2 on 2025-10-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0022_alter_historicalproduto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('conta', 'Conta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('bebida_nao_alcoolica', 'Bebida Não Alcoólica'), ('bebida_alcoolica', 'Bebida Alcoólica'), ('doces', 'Doces'), ('acessorios', 'Acessórios'), ('cigarros', 'Cigarros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('bebida_nao_alcoolica', 'Bebida Não Alcoólica'), ('bebida_alcoolica', 'Bebida Alcoólica'), ('doces', 'Doces'), ('acessorios', 'Acessórios'), ('cigarros', 'Cigarros')], max_length=20),
        ),
    ]
