# Generated by Django 5.2.8 on 2025-11-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0023_historicalproduto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
