# Generated by Django 5.2.8 on 2025-11-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0024_itemvenda_desconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='desconto',
        ),
    ]
