# Generated by Django 5.2 on 2025-11-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0025_remove_itemvenda_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
