# Generated by Django 5.2 on 2025-12-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0027_pdvsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
